### ISSUE TITLE
Использование мобильного Api

### ISSUE THREAD

**Issue by Bleser92** [Winster332/Yandex.Music.Api#1]
deleted

**Comment by Winster332** [comment]
@Bleser92 Из мобильного приложения не пытался. Но думаю проблемы быть не должно. 
Про авторизацию:
var api = new YandexMusicApi();
api.Authorize("username", "password');
и все следующие запросы будут происходить от авторизованного пользователя

**Comment by Bleser92** [comment]
@Winster332 Через 5 минут после того как написал, понял что при авторизации я получаю правильный токен, но использовал его не совсем правильно.
В итоге все работает =)
