### ISSUE TITLE
Ошибка при вызове метода ExtractStreamTrack

### ISSUE THREAD

**Issue by avmaisak** [Winster332/Yandex.Music.Api#7]
Шаги воспроизведения

- musicApi = new YandexMusicApi()
- musicApi.Authorize(login, passwd) - [OK]
- track = musicApi.GetTrack(myTrack) - [OK]
- var stream = musicApi.ExtractStreamTrack(track) [ FAIL ] 

System.Net.WebException: 'Этот хост неизвестен. Этот хост неизвестен.'

**Comment by Winster332** [comment]
Скорее всего яндекс изменил api. В данный момент нет времени заниматься проектом, если есть желание и возможность, можете сделать форк, или воспользоваться https://github.com/MarshalX/yandex-music-api, только он на python, они поддерживают проект в актуальном состоянии и в любой момент можно что-то спросить в [телеграм чатике](https://tx.me/yandex_music_api)
